### ISSUE TITLE
Call to a member function get() on null in message_ui_install()

### ISSUE THREAD

**Issue by stborchert** [RoySegall/message_ui#37]
### Problem/Motivation

While trying to install *Message* and *Message UI* (both are enabled by `core.extension.yml`) we get the following error:
```
Call to a member function get() on null in message_ui_install() (line 23 in message_ui.install)
```

It seems, the message-view as defined by *Message* in `views.view.message.yml` is not imported yet and cannot be loaded at this point.

### Proposed resolution

Wait for the configuration to be installed before accessing the view.

### Remaining tasks

Create pull request.

**Comment by RoySegall** [comment]
What is `core.extension.yml`. In reinstall today and that's worked for me.

**Comment by minorOffense** [comment]
I actually get that error during uninstall.

```yaml
module:
  auto_entitylabel: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  color: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  consumers: 0
  datetime: 0
  decoupled_router: 0
  dynamic_page_cache: 0
  encrypt: 0
  entity: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gnode: 0
  group: 0
  image: 0
  inline_entity_form: 0
  json_field: 0
  key: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  message: 0
  message_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  rest: 0
  serialization: 0
  simple_oauth: 0
  sshkey: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  terraform_state: 0
  text: 0
  tfa: 0
  toolbar: 0
  update: 0
  user: 0
  vault: 0
  views: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
```
