### ISSUE TITLE
When creating a message or enabling message UI set all the fields on the form as active

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/message_ui#6]
``` yml
message_ui.settings:
  type: config_object
  label: 'Field settings'
  mapping:
    update_tokens:
      type: message_ui.update_tokens
    show_preview:
      type: boolean
      label: 'Show Preview'
    anonymous:
      type: string
      label: 'Anonymous'
    dispaly_all_fields:
      type: boolean
      label: 'Display all form fields when creatina message type'
```
